### PR TITLE
#Rulq9fR2 Support WP-API Updates

### PR DESCRIPTION
**Pull request by josiahsprague**
This PR is for all changes required to support updating WP-API to v1.2.1

### CODE REVIEW

**Comment by josiahsprague** [comment]
To expose a custom field in the API, that field needs to be added to Types control (Types > Custom Fields Control > select field > Bulk Actions > Add to Types Control), and added to a group called Public (to create; Types > Custom Fields > Add New Group).

**Comment by josiahsprague** [comment]
@pushred I named the key that is added to the api `types_custom_meta`, basically `custom_meta` namespaced with `types_` for the Types plugin. To use this, we'll just have to update places where we're using the `post_meta` key to use `types_custom_meta` instead, or to check both.

I recommend that we install this Nadando update on production, then update our views and jungle-solidus to use the new key, and then we'll be safe to update the WP-API plugin.

**Comment by pushred** [comment]
:+1:

**Comment by josiahsprague** [comment]
`wpcf-byline` needs to be exposed in the API on JJ and possibly others.

**Pull request merged**
